[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Reporting-Endpoints = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {
          "url":"https://nordicgamelab.report-uri.com/a/d/g"
        }
      ],
      "include_subdomains":true
      }'''
    Content-Security-Policy = "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://*.nordicgamelab.org https://www.canva.com https://maxcdn.bootstrapcdn.com; script-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://*.nordicgamelab.org https://*google* https://maxcdn.bootstrapcdn.com https://js.hs-scripts.com https://js.hscollectedforms.net https://code.tidio.co https://js.sentry-cdn.com https://app.posthog.com https://tag.clearbitscripts.com; frame-src www.canva.com; img-src 'self' betteruptime.com data:; script-src-elem 'self' 'unsafe-inline' code.tidio.co fw-cdn.com js.hs-scripts.com js.sentry-cdn.com static.nordicgamelab.org tag.clearbitscripts.com www.google.com; style-src-attr 'unsafe-inline'; style-src-elem 'self' maxcdn.bootstrapcdn.com; report-uri https://nordicgamelab.report-uri.com/a/d/g; report-to default"

