[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Reporting-Endpoints = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {
          "url":"https://csp.nordicgamelab.org/a/d/g"
        }
      ],
      "include_subdomains":true
      }'''
    Content-Security-Policy = "default-src 'self' data: 'unsafe-inline' 'unsafe-eval' https://app.clearbit.com https://x.clearbitjs.com https://us.i.posthog.com https://us-assets.i.posthog.com https://widget-v4.tidiochat.com https://app.posthog.com https://tag.clearbitscripts.com https://code.tidio.co https://bam.nr-data.net https://js-agent.newrelic.com https://cdp.customer.io https://www.termsfeed.com https://browser.sentry-cdn.com https://static.nordicgamelab.org https://*.google.com https://*.gstatic.com https://js.sentry-cdn.com; child-src https://*.nordicgamelab.org; frame-ancestors https://*.nordicgamelab.org; upgrade-insecure-requests; report-uri https://csp.nordicgamelab.org/a/d/g; report-to default"

