[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Reporting-Endpoints = '''{
      "group":"default",
      "max_age":31536000,
      "endpoints":[
        {
          "url":"https://csp.nordicgamelab.org/a/d/g"
        }
      ],
      "include_subdomains":true
      }'''
    Content-Security-Policy = "frame-ancestors https://*.nordicgamelab.org; report-uri https://csp.nordicgamelab.org/a/d/g; report-to default"

