[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = "default-src none;"
    Reporting-Endpoints = '''
      csp-endpoint="https://csp.nordicgamelab.org/a/d/g?host=www.nordicgamelab.org"
    '''

