[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' 'inline' 'unsafe-inline' https://*.nordicgamelab.org https://www.canva.com  https://maxcdn.bootstrapcdn.com; style-src 'unsafe-inline' 'self' https://*.nordicgamelab.org https://maxcdn.bootstrapcdn.com 'inline' https://*google*; form-action 'self' https://*.nordicgamelab.org 'inline' 'unsafe-inline'; script-src 'unsafe-inline' 'self' https://*.nordicgamelab.org https://*google* https://maxcdn.bootstrapcdn.com  https://js.hs-scripts.com https://js.hscollectedforms.net https://code.tidio.co https://js.sentry-cdn.com https://app.posthog.com https://tag.clearbitscripts.com; connect-src 'self' https://*.nordicgamelab.org 'inline'; img-src '*'; base-uri 'self' https://*.nordicgamelab.org 'inline'; frame-ancestors 'none';"

