name: Auto approve

on: 
 pull_request_target:
 workflow_dispatch:
  inputs: 
      pullRequestNumber:
        description: Pull request number to auto-approve
        required: false

jobs:
 auto-approve:
  permissions:
    contents: read
    id-token: write
  runs-on: ubuntu-latest
  if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
  steps:
   - name: Import Secrets
     uses: Infisical/secrets-action@v1.0.15
     with:
          method: "oidc"
          env-slug: "dev"
          project-slug: "github-g0zh"
          identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
   - uses: hmarr/auto-approve-action@v4
     with:
      github-token: ${{env.NGLBOT}}
      review-message: "Auto approved automated PR"
      pull-request-number: ${{ github.event.inputs.pullRequestNumber }}
